-- ご利益カテゴリ シード（30種）
insert into goriyaku (slug, name, name_kana, icon, description, sort_order) values
('enmusubi',    '縁結び',         'えんむすび',     'heart.circle',                     '良縁・人間関係の縁を結ぶ',           1),
('renai',       '恋愛成就',       'れんあいじょうじゅ','heart.fill',                     '恋の成就・復縁',                     2),
('anzan',       '安産祈願',       'あんざん',       'figure.and.child.holdinghands',    '安産・母子の健康',                   3),
('kosodate',    '子宝・子育て',   'こだから',       'figure.2.and.child.holdinghands',  '子授け・子育て',                     4),
('kotsu_anzen', '交通安全',       'こうつうあんぜん','car.fill',                         '事故防止・道中の安全',               5),
('yakubarai',   '厄除け・厄払い', 'やくよけ',       'shield.lefthalf.filled',           '厄年・災難除け',                     6),
('byoki_heyu',  '病気平癒・健康', 'びょうきへいゆ', 'cross.case.fill',                  '病の治癒・無病息災',                 7),
('ekibyo',      '疫病退散',       'えきびょうたいさん','allergens',                     '感染症・疫病除け',                   8),
('gakugyo',     '学業成就・合格', 'がくぎょう',     'graduationcap.fill',               '受験合格・学業成就',                 9),
('shobai',      '商売繁盛',       'しょうばいはんじょう','yensign.circle.fill',         '商売・事業の繁栄',                  10),
('kinun',       '金運上昇',       'きんうん',       'banknote.fill',                    '財運・蓄財',                        11),
('shobu',       '勝負運・必勝',   'しょうぶうん',   'flag.checkered',                   '試合・勝負事の必勝',                12),
('shusse',      '出世開運',       'しゅっせかいうん','arrow.up.forward.circle.fill',    '昇進・運気上昇',                    13),
('kanai_anzen', '家内安全',       'かないあんぜん', 'house.fill',                       '家族の安全・平穏',                  14),
('shigoto',     '仕事・就職',     'しごと',         'briefcase.fill',                   '就職・転職・仕事運',                15),
('geino',       '芸能・技芸上達', 'げいのう',       'music.note',                       '芸事・音楽・技芸の上達',            16),
('gakumon',     '学問・知恵',     'がくもん',       'book.fill',                        '知恵・学識',                        17),
('kaiun',       '開運招福',       'かいうんしょうふく','sparkles',                      '総合運・福徳招来',                  18),
('majo_kekkai', '魔除け・方位除け','まよけ',         'hexagon.fill',                     '邪気・方位の災い除け',              19),
('suisan_noko', '五穀豊穣・豊漁', 'ごこくほうじょう','leaf.fill',                       '農業・漁業の実り',                  20),
('mizu_amagoi', '水・雨乞い・治水','みず',           'drop.fill',                        '水利・雨乞い・治水',                21),
('kaijo_anzen', '海上安全',       'かいじょうあんぜん','ferry.fill',                    '航海・漁の安全',                    22),
('bochu',       '武運・武道',     'ぶうん',         'figure.martial.arts',              '武術・武道・スポーツ',              23),
('enkiri',      '縁切り',         'えんきり',       'scissors',                         '悪縁を断つ',                        24),
('choju',       '長寿・延命',     'ちょうじゅ',     'hourglass',                        '健康長寿・延命',                    25),
('anchin',      '安鎮・国家安泰', 'あんちん',       'building.columns.fill',            '鎮護・国家安泰・平安',              26),
('bigan',       '美容・美願',     'びがん',         'sparkle',                          '美容・若返り',                      27),
('petto',       'ペット守護',     'ぺっと',         'pawprint.fill',                    '動物・ペットの守護',                28),
('jouju',       '心願成就',       'しんがんじょうじゅ','star.circle.fill',              '願い全般の成就',                    29),
('tabi_anzen',  '旅行安全',       'りょこうあんぜん','airplane',                        '旅・道中の安全',                    30)
on conflict (slug) do update set
  name = excluded.name, name_kana = excluded.name_kana, icon = excluded.icon,
  description = excluded.description, sort_order = excluded.sort_order;
